
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: GET

- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  # jsonData:
  #   httpMethod: GET
  #   serviceMap:
  #     datasourceUid: prometheus

- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true