services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      - OTEL_SERVICE_NAME=llm-tracing
      - OTEL_TRACES_EXPORTER=otlp 
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      # - GRPC_VERBOSITY=debug
      # - GRPC_TRACE=http,call_error,connectivity_state
    volumes:
      - ./src:/usr/src/app/
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317:4317
    volumes:
      - ./infra/otel/otel-collector.yaml:/etc/otel-collector.yaml
    command: --config=/etc/otel-collector.yaml

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./infra/otel/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090
    depends_on:
      - otel-collector

  tempo:
    image: grafana/tempo:latest
    ports:
      - 14268:14268
    volumes:
      - ./infra/otel/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]

  # Loki
  loki:
    image: grafana/loki:3.1.0
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -log.level=error
    volumes:
      - ./infra/otel/loki.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100


  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./infra/otel/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_SERVER_HTTP_PORT=3000
    ports:
      - 3000:3000