apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: apps-telemetry
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}

    exporters:
      debug:
        verbosity: detailed
      # otlphttp:
      #   endpoint: http://lgtm-loki-distributor.monitoring.svc.cluster.local:3100/otlp
      #   tls:
      #     insecure: true
      # prometheus:
      #   endpoint: 0.0.0.0:8888
      otlp:
        endpoint: lgtm-tempo-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          exporters: [debug]