# apiVersion: opentelemetry.io/v1beta1
# kind: OpenTelemetryCollector
# metadata:
#   name: sidecar-for-my-app
# spec:
#   mode: sidecar
#   config:
#     receivers:
#       otlp:
#         protocols:
#           grpc:
#           http:

#     exporters:
#       debug: {}
#       otlp:
#         endpoint: lgtm-tempo-distributor:4317
#         tls:
#           insecure: true

#     service:
#       pipelines:
#         traces:
#           receivers: [otlp]
#           exporters: [otlp]


apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:

    exporters:
      otlp:
        endpoint: lgtm-tempo-distributor:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]