replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "ihorhrysha/llm-tracing"
  tag: "0.6.0-0325379"
secret:
  name: llm-tracing-secrets
  key: api-key
  value: "tbd"
  env: OPENAI_API_KEY
volumes:
  - name: dev-mem
    hostPath:
      path: /dev/mem
      type: ""
volumeMounts:
  - mountPath: /dev/mem
    name: dev-mem
autoscaling:
  enabled: false
podAnnotations:
  sidecar.opentelemetry.io/inject: "true"
imagePullSecrets: {}
securityContext: {}
podSecurityContext: {}
