name: cicd

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }}/llm-tracing

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to github container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: release
        run: make release REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY

      - name: Clean
        run: make clean REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: echo "VERSION=$(make version)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.registry=strenv(REGISTRY)  | .image.repository=strenv(REPOSITORY) infra/chart/values.yaml
    
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.appVersion=strenv(VERSION)' infra/chart/Chart.yaml

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update Helm Chart version to $VERSION"
        git push