name: cicd

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }}/llm-tracing

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to github container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: release
        run: make release REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY

      - name: Clean
        run: make clean REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY

